---
title: "Are Summer Marriages Popular"
subtitle: "Toronto Marriages Deepdive"
author: 
  - Siddharth Gowda
thanks: "Open Data Toronto"
date: today
date-format: long
abstract: "Marriage can be one of the best days in a person's life, but it can be a hassle getting all family members together. So, people choose specific times to make sure some of their relatives can make it. So we wanted to know if summer marriages are more popular in Toronto because maybe people are more likely to take time off. We found that this is not the case. Marriages seem to be pretty evenly common across months in Toronto."
format: pdf
number-sections: true
bibliography: references.bib
---

```{r}
#| include: false
#| warning: false
#| message: false

library(tidyverse)
```

# Intro

You can and should cross-reference sections and sub-sections. We use @citeR, @citeOpendatatoronto

# Getting Data

```{r}
#| warning: false
#| message: false
# CREATING BAR CHART for marriages by month

marriage_data <- read_csv("../data/analysis_data/clean_marriage_data.csv")
head(marriage_data)

```

# Bar Chart

Here is the graph @fig-marriagesbymonth

```{r}
#| label: fig-marriagesbymonth
#| fig-cap: "Summer months do not appear to have more marriages"
#| echo: false
#| warning: false
#| message: false

marriage_data %>% ggplot(aes(x = month, y = marriages, fill=is_summer_month)) +
  geom_bar(stat = "identity") +
  labs(title = "Marriages by Month in Toronto (2000-2023)", 
       x = "Month", y = "Number of Marriages", 
       fill = "Is Summer Month") + 
  theme_minimal()

```

\newpage

# References


